name: Golang test
on:
  pull_request:
    branches:
    - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

jobs:
  # Check for vulnerability in code
  go-vuln:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Check for vulnerability in code
        run: go run golang.org/x/vuln/cmd/govulncheck@latest -format sarif ./...

  # Go test
  go-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"
        cache: true

    - uses: actions/setup-java@v4
      with:
        distribution: adopt-hotspot
        java-version: "23"

    - name: Download packages and mount tmpfs to /tmp
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        go get ./...
        sudo apt update
        sudo apt install -y proot || echo cannot install proot
        sudo mount -t tmpfs tmpfs /tmp

    - name: Test
      run: go test -timeout 0 -v ./...